export { default as Hero } from './Hero'
export { default as Services } from './Services'
export { default as About } from './About'
export { default as Testimonials } from './Testimonials'
export { default as Contact } from './Contact'
export { default as CTA } from './CTA'
export { default as EnterpriseSolutions } from './EnterpriseSolutions'
export { default as JoinPanel } from './JoinPanel'
